version: 2
jobs:
  deploy:
    docker:
      - image: icdocsoc/base-image:latest
        environment:
          ANDROID_HOME: /opt/Android
    steps:
      - checkout
      - run:
          name: "Decrypt keys"
          command: |
            openssl aes-256-cbc -d -in secrets/encrypted-keystore.properties -out keystore.properties -md sha256 -k $KEY
            openssl aes-256-cbc -d -in secrets/encrypted-catedroid-release-key.jks -out catedroid-release-key.jks -md sha256 -k $KEY
            # RUN openssl aes-256-cbc -e -in <file-in> -out <file-out> -k $KEY
            # in order to encrypt key
      - run: 
         name: "Building APK"
         command: source ~/.profile && ./gradlew build
      - run:
          name: "Publish Release on GitHub"
          command: |
            source ~/.profile && ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete $(git tag) ./app/build/outputs/apk/release/*.apk

  test:
    docker:
      - image: icdocsoc/base-image:latest
    steps:
      - checkout
      - run: ./test.sh

workflows:
  version: 2
  master_branch:
    jobs:
      - test:
          context: org-global
          filters:
            branches:
              only:
                - master
      - deploy:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only:
                - master
  dev_branch:
    jobs:
      - test:
          context: org-global
          filters:
            branches:
              ignore:
                - master
